### ISSUE TITLE
Localization bug

### ISSUE THREAD

**Issue by dartraiden** [lukasz1992/asuswrt-r3g#19]
http://router.asus.com/AdvanceCd_System_Content.asp

![Screenshot_2019-11-30 ASUS Wireless Router RT-MIR3G - System router asus com ](https://user-images.githubusercontent.com/5046855/69902981-c5a96a00-13a4-11ea-9a60-bfea34aa6b0f.png)

If current language is English, this label is Portugal
If current language is any other language, this label is English

**Comment by lukasz1992** [comment]
Sounds strange.. but you are actually right. This is a problem with sources imported from GPL.
I did a fix on master, because it was easy, however:
1) I will not produce a release only for this change
2) There are possible many bugs like that
If you compile current master, you'll have that issue fixed.
